# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitHandoff < Formula
  desc "Safely hand off branches between local and worktree checkouts"
  homepage "https://github.com/hanenao/git-handoff"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hanenao/git-handoff/releases/download/v0.0.2/git-handoff_v0.0.2_darwin_amd64.zip"
      sha256 "b54716e6f233c573591af3188665412bc682759f3caed088ce13cd74f70da025"

      define_method(:install) do
        bin.install "git-ho"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hanenao/git-handoff/releases/download/v0.0.2/git-handoff_v0.0.2_darwin_arm64.zip"
      sha256 "f93eb408479d578ed8535a27c855a48e7237ce936400c2c4a3c024cd5370181d"

      define_method(:install) do
        bin.install "git-ho"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanenao/git-handoff/releases/download/v0.0.2/git-handoff_v0.0.2_linux_amd64.tar.gz"
      sha256 "160778ed9be7c6132d427fb52153c7926a5892a4b6076d44caa23dadfd7c495d"
      define_method(:install) do
        bin.install "git-ho"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanenao/git-handoff/releases/download/v0.0.2/git-handoff_v0.0.2_linux_arm64.tar.gz"
      sha256 "f7e83668a749f68b6dffaa1adfdc52594cc3979bd03a9ac9fc025a3f25d4aee1"
      define_method(:install) do
        bin.install "git-ho"
      end
    end
  end
end
