# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitHandoff < Formula
  desc "Safely hand off branches between local and worktree checkouts"
  homepage "https://github.com/hanenao/git-handoff"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hanenao/git-handoff/releases/download/v0.0.3/git-handoff_v0.0.3_darwin_amd64.zip"
      sha256 "eadb3b0be97b49ba9c746369bbc38923d86581d46fb3c55495119766730ba072"

      define_method(:install) do
        bin.install "git-ho"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hanenao/git-handoff/releases/download/v0.0.3/git-handoff_v0.0.3_darwin_arm64.zip"
      sha256 "4dcefa0d5810fba9ef65cb150309df334c4ad1c09cb78cc88953df648792b0dd"

      define_method(:install) do
        bin.install "git-ho"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanenao/git-handoff/releases/download/v0.0.3/git-handoff_v0.0.3_linux_amd64.tar.gz"
      sha256 "c51120fde8d98f65741a967a0660fb69e7a78bc291df75c0b6a2b15d724ceae1"
      define_method(:install) do
        bin.install "git-ho"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hanenao/git-handoff/releases/download/v0.0.3/git-handoff_v0.0.3_linux_arm64.tar.gz"
      sha256 "03c8b4963f4406f71270bf52a31f22a2c5fbb675ae26c4383d4d9d2409ecbff6"
      define_method(:install) do
        bin.install "git-ho"
      end
    end
  end
end
